### ISSUE TITLE
Issues when using multitabs

### ISSUE THREAD

**Issue by ankitsam** [gilbitron/EasyCSRF#1]
CSRF token is generated for every request, makes it unable to verify when multiple tabs are opened.

**Comment by fadlisaad** [comment]
Did you try the reusable option?

**Comment by ankitsam** [comment]
Yes i have tried that, I think reusable options is for ajax application where same token can be sent to server again n again  and it would still be valid, but when i open 2-3 tabs, a new token is generated in each tab.

**Comment by fadlisaad** [comment]
I got an idea, however its up to you on how to achieve it. Once you open the page, store the token in a session. Later, if you open the same page in new tab, your code need to check if the token in the session is exist, so the new open tab no need to generate new token.
