### ISSUE TITLE
[CRITICAL] This library is absolutely insecure

### ISSUE THREAD

**Issue by dzentota** [gilbitron/EasyCSRF#9]
It looks like this library was intentionally created to be insecure.

1. Type juggling
```php
function referralHash()
{
    return sha1('192.168.0.1' . 'aMozilla Firefox');
}

function randomString()
{
    return sha1(random_bytes(32));
}

$time = time();
$token = $time . referralHash() . randomString(32);
echo $time, PHP_EOL;
echo $token, PHP_EOL;
var_dump($time == $token);
```
till the PHP 8.0 `123 == '123abc'`
that's why it's critical to have `===` here https://github.com/gilbitron/EasyCSRF/blob/73a1a13fd86eb16533a43170e52af8b8fe72ba71/src/EasyCSRF.php#L74

2. `mt_rand` does not generate cryptographically secure values. Given two mt_rand() output values separated by 226 others, it is [possible to compute, without any bruteforce](https://www.ambionics.io/blog/php-mt-rand-prediction), the original seed, and therefore obtain any previous or subsequent mt_rand() output, effectively breaking the PRNG 
Consider reworking randomString() to somethiing like:
```php
protected function randomString(): string
{
    return sha1(random_bytes(32));
}
```

3. (Just a question)What is the purpose of referralHash()? In CSRF attacks all the requests come from the legitimate user so `randomString() + referralHash()` is as much secure as `randomString()`

**Comment by gilbitron** [comment]
> It looks like this library was intentionally created to be insecure.

FYI maintainers don't respond very well to starting tickets like this with sensationalist opinions that happen to be incorrect. Could this library be improved? Sure. Was this library "intentionally created to be insecure"? No.

If you have any suggestions for improvements, I'd be happy to review a PR.

**Comment by dzentota** [comment]
Making a PR is not a problem. The problem is that your library has 77 stars and people think it protects them from CSRF, while it is not.
My comment was for possible users of your library, not for you :-)
